platform :ios, “7.0”
pod 'LBXScan', '~> 1.1.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJExtension', '~> 2.5.12'
pod 'MJRefresh', '~> 2.4.11'
pod 'UMengAnalytics'
pod 'Masonry', '~> 0.6.3'
pod 'SWTableViewCell', '~> 0.3.7'